// This file is auto-generated by drizzle-kit introspect
// Do not modify manually - changes will be overwritten
//
// Add new table definitions below, then run upgrade.sh to sync to database

import { sql } from "drizzle-orm";
import {
  pgTable,
  text,
  varchar,
  timestamp,
  boolean,
  integer,
  serial,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";

// ============================================================================
// Table definitions will be generated here by drizzle-kit introspect
// ============================================================================
